# Generated by Django 5.2.8 on 2025-11-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='fixed_expenses',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Despesas fixas', max_digits=10),
        ),
        migrations.AddField(
            model_name='note',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor por hora', max_digits=10),
        ),
        migrations.AddField(
            model_name='note',
            name='hours',
            field=models.IntegerField(default=0, help_text='Horas gastos'),
        ),
        migrations.AddField(
            model_name='note',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custo do material', max_digits=10),
        ),
        migrations.AddField(
            model_name='note',
            name='minutes',
            field=models.IntegerField(default=0, help_text='Minutos gastos'),
        ),
        migrations.AddField(
            model_name='note',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Margem de lucro', max_digits=10),
        ),
        migrations.AddField(
            model_name='note',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Preço total (após cálculo)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text='Nome da peça', max_length=200),
        ),
    ]
